name: Build

## WARNING ##
# Currently not really working.

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: install dependencies
        run: npm install
      - name: build
        run: |
          npm run tauri build
          cd src-tauri/target/release/bundle/macos
          chmod a+x "Jell Machine.app/Contents/MacOS/Jell Machine"
          tar -cvf ../../MacOS.tar Jell\ Machine.app
          cd ../../../../..
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: MacOS
          path: src-tauri/target/release/MacOS.tar
          if-no-files-found: error
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: install dependencies
        run: npm install
      - name: build
        run: npm run tauri build
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Windows
          path: src-tauri/target/release/bundle/msi
          if-no-files-found: error
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: install dependencies
        run: |
          npm install
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev librsvg2-dev
      - name: build
        run: npm run tauri build
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Linux
          path: src-tauri/target/release/bundle/appimage
          if-no-files-found: error
  # build:
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Install packages
  #       run: npm install
  #     - name: Build project for Windows
  #       run: npm run build:electron:windows
  #     - name: Upload Windows build
  #       uses: actions/upload-artifact@v2.2.4
  #       with:
  #         name: Windows
  #         path: dist/Jell Machine-win32-x64
  #         if-no-files-found: error
  #     - name: Build project for Linux
  #       run: npm run build:electron:linux
  #     - name: Upload Linux build
  #       uses: actions/upload-artifact@v2.2.4
  #       with:
  #         name: Linux
  #         path: dist/Jell Machine-linux-x64
  #         if-no-files-found: error
  # build-mac:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Install packages
  #       run: npm install
  #     - name: Build project for Mac
  #       run: |
  #         npm run build:electron:mac
  #         chmod a+x "dist/Jell Machine-darwin-x64/Jell Machine.app/Contents/MacOS/Jell Machine"
  #         cd dist/Jell\ Machine-darwin-x64
  #         tar -cvf ../MacOS.tar Jell\ Machine.app
  #         cd ../..
  #     - name: Upload Mac build
  #       uses: actions/upload-artifact@v2.2.4
  #       with:
  #         name: MacOS
  #         path: dist/MacOS.tar
  #         if-no-files-found: error
